name: Links (PR)

on:
  pull_request:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links in Markdown
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --config lychee.toml
            --verbose
            --no-progress
            **/*.md
